PRESETS = {
    "chat": {
        "input_gain_db": 3.0,
        "noise_gate_threshold_db": -50.0,
        "noise_gate_floor": 0.25,
        "highpass_hz": 80.0,
        "deesser_threshold": 0.08,
        "deesser_ratio": 3.0,
        "compressor_threshold_db": -20.0,
        "compressor_ratio": 3.0,
        "makeup_gain_db": 2.0,
        "limiter_threshold": 0.92,
    },
    "sing": {
        "input_gain_db": 1.0,
        "noise_gate_threshold_db": -55.0,
        "noise_gate_floor": 0.35,
        "highpass_hz": 60.0,
        "deesser_threshold": 0.10,
        "deesser_ratio": 2.2,
        "compressor_threshold_db": -18.0,
        "compressor_ratio": 2.6,
        "makeup_gain_db": 1.5,
        "limiter_threshold": 0.95,
    },
    "radio": {
        "input_gain_db": 4.0,
        "noise_gate_threshold_db": -52.0,
        "noise_gate_floor": 0.22,
        "highpass_hz": 95.0,
        "deesser_threshold": 0.07,
        "deesser_ratio": 3.4,
        "compressor_threshold_db": -24.0,
        "compressor_ratio": 3.8,
        "makeup_gain_db": 3.0,
        "limiter_threshold": 0.90,
    },
    "pk": {
        "input_gain_db": 5.0,
        "noise_gate_threshold_db": -48.0,
        "noise_gate_floor": 0.20,
        "highpass_hz": 100.0,
        "deesser_threshold": 0.09,
        "deesser_ratio": 2.8,
        "compressor_threshold_db": -22.0,
        "compressor_ratio": 4.0,
        "makeup_gain_db": 4.0,
        "limiter_threshold": 0.88,
    },
}
